### ISSUE TITLE
Getting FATA[0022] print list item: print list item: object does not implement the Object interfaces on OCP 4.5.18

### ISSUE THREAD

**Issue by lbohnsac** [corneliusweig/ketall#112]
**Describe the bug**
Just installed get-all v1.3.5 on an OCP 4.5.18 cluster

oc get-all
WARN[0010] Cannot fetch: the server does not allow this method on the requested resource 
WARN[0020] Cannot fetch: Unable to list "image.openshift.io/v1, Resource=imagestreamimages": the server could not find the requested resource 
FATA[0022] print list item: print list item: object does not implement the Object interfaces 

oc version
Client Version: 4.6.4
Server Version: 4.5.18
Kubernetes Version: v1.18.3+ac53d20

**To Reproduce**
see above

**Expected behavior**
regular output

**Desktop (please complete the following information):**
 - output of `ketall version --full`:
oc get-all version --full
ketall:     v1.3.5
platform:   linux/amd64
git commit: 460494e2af1eba0c8711882106b64e9a6a042fae
build date: 2020-09-23T08:45:20Z
go version: go1.15.2
compiler:   gc

cat /etc/redhat-release 
Red Hat Enterprise Linux release 8.1 (Ootpa)

**Debug output**
oc get-all -v debug
time="2020-11-18T09:16:58+01:00" level=debug msg="Set log-level to debug"
time="2020-11-18T09:16:58+01:00" level=debug msg="Excluding events"
time="2020-11-18T09:16:58+01:00" level=debug msg="Excluding events.events.k8s.io"
time="2020-11-18T09:16:58+01:00" level=debug msg="Excluding pods.metrics.k8s.io"
time="2020-11-18T09:16:58+01:00" level=debug msg="Resources to fetch: [componentstatuses configmaps endpoints limitranges namespaces nodes persistentvolumeclaims persistentvolumes pods podtemplates replicationcontrollers resourcequotas secrets serviceaccounts services mutatingwebhookconfigurations.admissionregistration.k8s.io validatingwebhookconfigurations.admissionregistration.k8s.io customresourcedefinitions.apiextensions.k8s.io apiservices.apiregistration.k8s.io controllerrevisions.apps daemonsets.apps deployments.apps replicasets.apps statefulsets.apps deploymentconfigs.apps.openshift.io applications.argoproj.io appprojects.argoproj.io argocdexports.argoproj.io argocds.argoproj.io clusterworkflowtemplates.argoproj.io cronworkflows.argoproj.io workfloweventbindings.argoproj.io workflows.argoproj.io workflowtemplates.argoproj.io clusterrolebindings.authorization.openshift.io clusterroles.authorization.openshift.io rolebindingrestrictions.authorization.openshift.io rolebindings.authorization.openshift.io roles.authorization.openshift.io horizontalpodautoscalers.autoscaling clusterautoscalers.autoscaling.openshift.io machineautoscalers.autoscaling.openshift.io cronjobs.batch jobs.batch sealedsecrets.bitnami.com buildconfigs.build.openshift.io builds.build.openshift.io certificatesigningrequests.certificates.k8s.io credentialsrequests.cloudcredential.openshift.io apiservers.config.openshift.io authentications.config.openshift.io builds.config.openshift.io clusteroperators.config.openshift.io clusterversions.config.openshift.io consoles.config.openshift.io dnses.config.openshift.io featuregates.config.openshift.io images.config.openshift.io infrastructures.config.openshift.io ingresses.config.openshift.io networks.config.openshift.io oauths.config.openshift.io operatorhubs.config.openshift.io projects.config.openshift.io proxies.config.openshift.io schedulers.config.openshift.io consoleclidownloads.console.openshift.io consoleexternalloglinks.console.openshift.io consolelinks.console.openshift.io consolenotifications.console.openshift.io consoleyamlsamples.console.openshift.io leases.coordination.k8s.io endpointslices.discovery.k8s.io ingresses.extensions flowschemas.flowcontrol.apiserver.k8s.io prioritylevelconfigurations.flowcontrol.apiserver.k8s.io images.image.openshift.io imagestreamimages.image.openshift.io imagestreams.image.openshift.io imagestreamtags.image.openshift.io imagetags.image.openshift.io configs.imageregistry.operator.openshift.io imagepruners.imageregistry.operator.openshift.io dnsrecords.ingress.operator.openshift.io network-attachment-definitions.k8s.cni.cncf.io machinehealthchecks.machine.openshift.io machines.machine.openshift.io machinesets.machine.openshift.io containerruntimeconfigs.machineconfiguration.openshift.io controllerconfigs.machineconfiguration.openshift.io kubeletconfigs.machineconfiguration.openshift.io machineconfigpools.machineconfiguration.openshift.io machineconfigs.machineconfiguration.openshift.io baremetalhosts.metal3.io provisionings.metal3.io nodes.metrics.k8s.io storagestates.migration.k8s.io storageversionmigrations.migration.k8s.io alertmanagers.monitoring.coreos.com podmonitors.monitoring.coreos.com prometheuses.monitoring.coreos.com prometheusrules.monitoring.coreos.com servicemonitors.monitoring.coreos.com thanosrulers.monitoring.coreos.com clusternetworks.network.openshift.io egressnetworkpolicies.network.openshift.io hostsubnets.network.openshift.io netnamespaces.network.openshift.io operatorpkis.network.operator.openshift.io ingressclasses.networking.k8s.io ingresses.networking.k8s.io networkpolicies.networking.k8s.io runtimeclasses.node.k8s.io oauthaccesstokens.oauth.openshift.io oauthauthorizetokens.oauth.openshift.io oauthclientauthorizations.oauth.openshift.io oauthclients.oauth.openshift.io authentications.operator.openshift.io cloudcredentials.operator.openshift.io configs.operator.openshift.io consoles.operator.openshift.io csisnapshotcontrollers.operator.openshift.io dnses.operator.openshift.io etcds.operator.openshift.io imagecontentsourcepolicies.operator.openshift.io ingresscontrollers.operator.openshift.io kubeapiservers.operator.openshift.io kubecontrollermanagers.operator.openshift.io kubeschedulers.operator.openshift.io kubestorageversionmigrators.operator.openshift.io networks.operator.openshift.io openshiftapiservers.operator.openshift.io openshiftcontrollermanagers.operator.openshift.io servicecas.operator.openshift.io catalogsources.operators.coreos.com clusterserviceversions.operators.coreos.com installplans.operators.coreos.com operatorgroups.operators.coreos.com operatorsources.operators.coreos.com subscriptions.operators.coreos.com packagemanifests.packages.operators.coreos.com poddisruptionbudgets.policy podsecuritypolicies.policy projectrequests.project.openshift.io projects.project.openshift.io appliedclusterresourcequotas.quota.openshift.io clusterresourcequotas.quota.openshift.io clusterrolebindings.rbac.authorization.k8s.io clusterroles.rbac.authorization.k8s.io rolebindings.rbac.authorization.k8s.io roles.rbac.authorization.k8s.io routes.route.openshift.io configs.samples.operator.openshift.io priorityclasses.scheduling.k8s.io rangeallocations.security.openshift.io securitycontextconstraints.security.openshift.io volumesnapshotclasses.snapshot.storage.k8s.io volumesnapshotcontents.snapshot.storage.k8s.io volumesnapshots.snapshot.storage.k8s.io csidrivers.storage.k8s.io csinodes.storage.k8s.io storageclasses.storage.k8s.io volumeattachments.storage.k8s.io brokertemplateinstances.template.openshift.io templateinstances.template.openshift.io templates.template.openshift.io profiles.tuned.openshift.io tuneds.tuned.openshift.io groups.user.openshift.io identities.user.openshift.io useridentitymappings.user.openshift.io users.user.openshift.io ippools.whereabouts.cni.cncf.io]"
time="2020-11-18T09:17:04+01:00" level=debug msg="Initial fetchResourcesBulk done (5s)"
time="2020-11-18T09:17:04+01:00" level=debug msg="Fetch resources incrementally"
time="2020-11-18T09:17:04+01:00" level=debug msg="Resources to fetch: [ippools.whereabouts.cni.cncf.io]"
time="2020-11-18T09:17:04+01:00" level=debug msg="Resources to fetch: [componentstatuses]"
time="2020-11-18T09:17:04+01:00" level=debug msg="Resources to fetch: [kubestorageversionmigrators.operator.openshift.io]"
time="2020-11-18T09:17:04+01:00" level=debug msg="Resources to fetch: [configmaps]"
time="2020-11-18T09:17:04+01:00" level=debug msg="Resources to fetch: [endpoints]"
time="2020-11-18T09:17:04+01:00" level=debug msg="Resources to fetch: [networks.operator.openshift.io]"
time="2020-11-18T09:17:04+01:00" level=debug msg="Resources to fetch: [openshiftapiservers.operator.openshift.io]"
time="2020-11-18T09:17:04+01:00" level=debug msg="Resources to fetch: [openshiftcontrollermanagers.operator.openshift.io]"
time="2020-11-18T09:17:04+01:00" level=debug msg="Resources to fetch: [servicecas.operator.openshift.io]"
time="2020-11-18T09:17:04+01:00" level=debug msg="Resources to fetch: [catalogsources.operators.coreos.com]"
time="2020-11-18T09:17:04+01:00" level=debug msg="Resources to fetch: [clusterserviceversions.operators.coreos.com]"
time="2020-11-18T09:17:04+01:00" level=debug msg="Resources to fetch: [installplans.operators.coreos.com]"
time="2020-11-18T09:17:04+01:00" level=debug msg="Resources to fetch: [operatorgroups.operators.coreos.com]"
time="2020-11-18T09:17:04+01:00" level=debug msg="Resources to fetch: [operatorsources.operators.coreos.com]"
time="2020-11-18T09:17:04+01:00" level=debug msg="Resources to fetch: [subscriptions.operators.coreos.com]"
time="2020-11-18T09:17:04+01:00" level=debug msg="Resources to fetch: [packagemanifests.packages.operators.coreos.com]"
time="2020-11-18T09:17:04+01:00" level=debug msg="Resources to fetch: [poddisruptionbudgets.policy]"
time="2020-11-18T09:17:04+01:00" level=debug msg="Resources to fetch: [podsecuritypolicies.policy]"
time="2020-11-18T09:17:04+01:00" level=debug msg="Resources to fetch: [projectrequests.project.openshift.io]"
time="2020-11-18T09:17:04+01:00" level=debug msg="Resources to fetch: [projects.project.openshift.io]"
time="2020-11-18T09:17:04+01:00" level=debug msg="Resources to fetch: [appliedclusterresourcequotas.quota.openshift.io]"
time="2020-11-18T09:17:04+01:00" level=debug msg="Resources to fetch: [clusterresourcequotas.quota.openshift.io]"
time="2020-11-18T09:17:04+01:00" level=debug msg="Resources to fetch: [clusterrolebindings.rbac.authorization.k8s.io]"
time="2020-11-18T09:17:04+01:00" level=debug msg="Resources to fetch: [clusterroles.rbac.authorization.k8s.io]"
time="2020-11-18T09:17:04+01:00" level=debug msg="Resources to fetch: [rolebindings.rbac.authorization.k8s.io]"
time="2020-11-18T09:17:04+01:00" level=debug msg="Resources to fetch: [roles.rbac.authorization.k8s.io]"
time="2020-11-18T09:17:04+01:00" level=debug msg="Resources to fetch: [routes.route.openshift.io]"
time="2020-11-18T09:17:04+01:00" level=debug msg="Resources to fetch: [configs.samples.operator.openshift.io]"
time="2020-11-18T09:17:04+01:00" level=debug msg="Resources to fetch: [rangeallocations.security.openshift.io]"
time="2020-11-18T09:17:04+01:00" level=debug msg="Resources to fetch: [securitycontextconstraints.security.openshift.io]"
time="2020-11-18T09:17:04+01:00" level=debug msg="Resources to fetch: [volumesnapshotclasses.snapshot.storage.k8s.io]"
time="2020-11-18T09:17:04+01:00" level=debug msg="Resources to fetch: [volumesnapshotcontents.snapshot.storage.k8s.io]"
time="2020-11-18T09:17:04+01:00" level=debug msg="Resources to fetch: [volumesnapshots.snapshot.storage.k8s.io]"
time="2020-11-18T09:17:04+01:00" level=debug msg="Resources to fetch: [csidrivers.storage.k8s.io]"
time="2020-11-18T09:17:04+01:00" level=debug msg="Resources to fetch: [csinodes.storage.k8s.io]"
time="2020-11-18T09:17:04+01:00" level=debug msg="Resources to fetch: [storageclasses.storage.k8s.io]"
time="2020-11-18T09:17:04+01:00" level=debug msg="Resources to fetch: [volumeattachments.storage.k8s.io]"
time="2020-11-18T09:17:04+01:00" level=debug msg="Resources to fetch: [brokertemplateinstances.template.openshift.io]"
time="2020-11-18T09:17:04+01:00" level=debug msg="Resources to fetch: [templateinstances.template.openshift.io]"
time="2020-11-18T09:17:04+01:00" level=debug msg="Resources to fetch: [templates.template.openshift.io]"
time="2020-11-18T09:17:04+01:00" level=debug msg="Resources to fetch: [profiles.tuned.openshift.io]"
time="2020-11-18T09:17:04+01:00" level=debug msg="Resources to fetch: [tuneds.tuned.openshift.io]"
time="2020-11-18T09:17:04+01:00" level=debug msg="Resources to fetch: [groups.user.openshift.io]"
time="2020-11-18T09:17:04+01:00" level=debug msg="Resources to fetch: [identities.user.openshift.io]"
time="2020-11-18T09:17:04+01:00" level=debug msg="Resources to fetch: [useridentitymappings.user.openshift.io]"
time="2020-11-18T09:17:04+01:00" level=debug msg="Resources to fetch: [users.user.openshift.io]"
time="2020-11-18T09:17:04+01:00" level=debug msg="Resources to fetch: [credentialsrequests.cloudcredential.openshift.io]"
time="2020-11-18T09:17:04+01:00" level=debug msg="Resources to fetch: [apiservers.config.openshift.io]"
time="2020-11-18T09:17:04+01:00" level=debug msg="Resources to fetch: [authentications.config.openshift.io]"
time="2020-11-18T09:17:04+01:00" level=debug msg="Resources to fetch: [builds.config.openshift.io]"
time="2020-11-18T09:17:04+01:00" level=debug msg="Resources to fetch: [clusteroperators.config.openshift.io]"
time="2020-11-18T09:17:04+01:00" level=debug msg="Resources to fetch: [clusterversions.config.openshift.io]"
time="2020-11-18T09:17:04+01:00" level=debug msg="Resources to fetch: [consoles.config.openshift.io]"
time="2020-11-18T09:17:04+01:00" level=debug msg="Resources to fetch: [dnses.config.openshift.io]"
time="2020-11-18T09:17:04+01:00" level=debug msg="Resources to fetch: [featuregates.config.openshift.io]"
time="2020-11-18T09:17:04+01:00" level=debug msg="Resources to fetch: [images.config.openshift.io]"
time="2020-11-18T09:17:04+01:00" level=debug msg="Resources to fetch: [infrastructures.config.openshift.io]"
time="2020-11-18T09:17:04+01:00" level=debug msg="Resources to fetch: [ingresses.config.openshift.io]"
time="2020-11-18T09:17:04+01:00" level=debug msg="Resources to fetch: [networks.config.openshift.io]"
time="2020-11-18T09:17:04+01:00" level=debug msg="Resources to fetch: [oauths.config.openshift.io]"
time="2020-11-18T09:17:04+01:00" level=debug msg="Resources to fetch: [operatorhubs.config.openshift.io]"
time="2020-11-18T09:17:04+01:00" level=debug msg="Resources to fetch: [projects.config.openshift.io]"
time="2020-11-18T09:17:04+01:00" level=debug msg="Resources to fetch: [proxies.config.openshift.io]"
time="2020-11-18T09:17:04+01:00" level=debug msg="Resources to fetch: [schedulers.config.openshift.io]"
time="2020-11-18T09:17:04+01:00" level=debug msg="Resources to fetch: [priorityclasses.scheduling.k8s.io]"
time="2020-11-18T09:17:04+01:00" level=debug msg="Resources to fetch: [consoleclidownloads.console.openshift.io]"
time="2020-11-18T09:17:04+01:00" level=debug msg="Resources to fetch: [consoleexternalloglinks.console.openshift.io]"
time="2020-11-18T09:17:04+01:00" level=debug msg="Resources to fetch: [consolelinks.console.openshift.io]"
time="2020-11-18T09:17:07+01:00" level=debug msg="Resources to fetch: [consolenotifications.console.openshift.io]"
time="2020-11-18T09:17:09+01:00" level=debug msg="Resources to fetch: [consoleyamlsamples.console.openshift.io]"
time="2020-11-18T09:17:09+01:00" level=debug msg="Resources to fetch: [leases.coordination.k8s.io]"
time="2020-11-18T09:17:09+01:00" level=debug msg="Resources to fetch: [endpointslices.discovery.k8s.io]"
time="2020-11-18T09:17:09+01:00" level=debug msg="Resources to fetch: [ingresses.extensions]"
time="2020-11-18T09:17:09+01:00" level=debug msg="Resources to fetch: [flowschemas.flowcontrol.apiserver.k8s.io]"
time="2020-11-18T09:17:09+01:00" level=warning msg="Cannot fetch: the server does not allow this method on the requested resource"
time="2020-11-18T09:17:09+01:00" level=debug msg="Resources to fetch: [prioritylevelconfigurations.flowcontrol.apiserver.k8s.io]"
time="2020-11-18T09:17:09+01:00" level=debug msg="Resources to fetch: [images.image.openshift.io]"
time="2020-11-18T09:17:09+01:00" level=debug msg="Resources to fetch: [imagestreamimages.image.openshift.io]"
time="2020-11-18T09:17:09+01:00" level=debug msg="Resources to fetch: [imagestreams.image.openshift.io]"
time="2020-11-18T09:17:09+01:00" level=debug msg="Resources to fetch: [imagestreamtags.image.openshift.io]"
time="2020-11-18T09:17:09+01:00" level=debug msg="Resources to fetch: [imagetags.image.openshift.io]"
time="2020-11-18T09:17:09+01:00" level=debug msg="Resources to fetch: [configs.imageregistry.operator.openshift.io]"
time="2020-11-18T09:17:09+01:00" level=debug msg="Resources to fetch: [imagepruners.imageregistry.operator.openshift.io]"
time="2020-11-18T09:17:09+01:00" level=debug msg="Resources to fetch: [dnsrecords.ingress.operator.openshift.io]"
time="2020-11-18T09:17:09+01:00" level=debug msg="Resources to fetch: [network-attachment-definitions.k8s.cni.cncf.io]"
time="2020-11-18T09:17:09+01:00" level=debug msg="Resources to fetch: [machinehealthchecks.machine.openshift.io]"
time="2020-11-18T09:17:09+01:00" level=debug msg="Resources to fetch: [machines.machine.openshift.io]"
time="2020-11-18T09:17:09+01:00" level=debug msg="Resources to fetch: [machinesets.machine.openshift.io]"
time="2020-11-18T09:17:09+01:00" level=debug msg="Resources to fetch: [containerruntimeconfigs.machineconfiguration.openshift.io]"
time="2020-11-18T09:17:09+01:00" level=debug msg="Resources to fetch: [controllerconfigs.machineconfiguration.openshift.io]"
time="2020-11-18T09:17:10+01:00" level=debug msg="Resources to fetch: [kubeletconfigs.machineconfiguration.openshift.io]"
time="2020-11-18T09:17:10+01:00" level=debug msg="Resources to fetch: [machineconfigpools.machineconfiguration.openshift.io]"
time="2020-11-18T09:17:10+01:00" level=debug msg="Resources to fetch: [machineconfigs.machineconfiguration.openshift.io]"
time="2020-11-18T09:17:10+01:00" level=debug msg="Resources to fetch: [baremetalhosts.metal3.io]"
time="2020-11-18T09:17:10+01:00" level=debug msg="Resources to fetch: [provisionings.metal3.io]"
time="2020-11-18T09:17:10+01:00" level=debug msg="Resources to fetch: [nodes.metrics.k8s.io]"
time="2020-11-18T09:17:10+01:00" level=debug msg="Resources to fetch: [storagestates.migration.k8s.io]"
time="2020-11-18T09:17:10+01:00" level=debug msg="Resources to fetch: [storageversionmigrations.migration.k8s.io]"
time="2020-11-18T09:17:10+01:00" level=debug msg="Resources to fetch: [alertmanagers.monitoring.coreos.com]"
time="2020-11-18T09:17:10+01:00" level=debug msg="Resources to fetch: [podmonitors.monitoring.coreos.com]"
time="2020-11-18T09:17:10+01:00" level=debug msg="Resources to fetch: [prometheuses.monitoring.coreos.com]"
time="2020-11-18T09:17:10+01:00" level=debug msg="Resources to fetch: [prometheusrules.monitoring.coreos.com]"
time="2020-11-18T09:17:10+01:00" level=debug msg="Resources to fetch: [servicemonitors.monitoring.coreos.com]"
time="2020-11-18T09:17:10+01:00" level=debug msg="Resources to fetch: [thanosrulers.monitoring.coreos.com]"
time="2020-11-18T09:17:10+01:00" level=debug msg="Resources to fetch: [clusternetworks.network.openshift.io]"
time="2020-11-18T09:17:10+01:00" level=debug msg="Resources to fetch: [egressnetworkpolicies.network.openshift.io]"
time="2020-11-18T09:17:10+01:00" level=debug msg="Resources to fetch: [hostsubnets.network.openshift.io]"
time="2020-11-18T09:17:10+01:00" level=debug msg="Resources to fetch: [netnamespaces.network.openshift.io]"
time="2020-11-18T09:17:10+01:00" level=debug msg="Resources to fetch: [operatorpkis.network.operator.openshift.io]"
time="2020-11-18T09:17:10+01:00" level=debug msg="Resources to fetch: [ingressclasses.networking.k8s.io]"
time="2020-11-18T09:17:10+01:00" level=debug msg="Resources to fetch: [ingresses.networking.k8s.io]"
time="2020-11-18T09:17:10+01:00" level=debug msg="Resources to fetch: [networkpolicies.networking.k8s.io]"
time="2020-11-18T09:17:10+01:00" level=debug msg="Resources to fetch: [runtimeclasses.node.k8s.io]"
time="2020-11-18T09:17:10+01:00" level=debug msg="Resources to fetch: [oauthaccesstokens.oauth.openshift.io]"
time="2020-11-18T09:17:10+01:00" level=debug msg="Resources to fetch: [oauthauthorizetokens.oauth.openshift.io]"
time="2020-11-18T09:17:10+01:00" level=debug msg="Resources to fetch: [oauthclientauthorizations.oauth.openshift.io]"
time="2020-11-18T09:17:10+01:00" level=debug msg="Resources to fetch: [oauthclients.oauth.openshift.io]"
time="2020-11-18T09:17:11+01:00" level=debug msg="Resources to fetch: [authentications.operator.openshift.io]"
time="2020-11-18T09:17:11+01:00" level=debug msg="Resources to fetch: [cloudcredentials.operator.openshift.io]"
time="2020-11-18T09:17:11+01:00" level=debug msg="Resources to fetch: [configs.operator.openshift.io]"
time="2020-11-18T09:17:11+01:00" level=debug msg="Resources to fetch: [consoles.operator.openshift.io]"
time="2020-11-18T09:17:11+01:00" level=debug msg="Resources to fetch: [csisnapshotcontrollers.operator.openshift.io]"
time="2020-11-18T09:17:11+01:00" level=debug msg="Resources to fetch: [dnses.operator.openshift.io]"
time="2020-11-18T09:17:11+01:00" level=debug msg="Resources to fetch: [etcds.operator.openshift.io]"
time="2020-11-18T09:17:11+01:00" level=debug msg="Resources to fetch: [imagecontentsourcepolicies.operator.openshift.io]"
time="2020-11-18T09:17:11+01:00" level=debug msg="Resources to fetch: [ingresscontrollers.operator.openshift.io]"
time="2020-11-18T09:17:11+01:00" level=debug msg="Resources to fetch: [kubeapiservers.operator.openshift.io]"
time="2020-11-18T09:17:11+01:00" level=debug msg="Resources to fetch: [kubecontrollermanagers.operator.openshift.io]"
time="2020-11-18T09:17:11+01:00" level=debug msg="Resources to fetch: [kubeschedulers.operator.openshift.io]"
time="2020-11-18T09:17:11+01:00" level=debug msg="Resources to fetch: [limitranges]"
time="2020-11-18T09:17:11+01:00" level=debug msg="Resources to fetch: [namespaces]"
time="2020-11-18T09:17:12+01:00" level=debug msg="Resources to fetch: [nodes]"
time="2020-11-18T09:17:12+01:00" level=debug msg="Resources to fetch: [persistentvolumeclaims]"
time="2020-11-18T09:17:12+01:00" level=debug msg="Resources to fetch: [persistentvolumes]"
time="2020-11-18T09:17:12+01:00" level=debug msg="Resources to fetch: [pods]"
time="2020-11-18T09:17:12+01:00" level=debug msg="Resources to fetch: [podtemplates]"
time="2020-11-18T09:17:12+01:00" level=debug msg="Resources to fetch: [replicationcontrollers]"
time="2020-11-18T09:17:12+01:00" level=debug msg="Resources to fetch: [resourcequotas]"
time="2020-11-18T09:17:12+01:00" level=debug msg="Resources to fetch: [secrets]"
time="2020-11-18T09:17:12+01:00" level=debug msg="Resources to fetch: [serviceaccounts]"
time="2020-11-18T09:17:12+01:00" level=debug msg="Resources to fetch: [services]"
time="2020-11-18T09:17:13+01:00" level=debug msg="Resources to fetch: [mutatingwebhookconfigurations.admissionregistration.k8s.io]"
time="2020-11-18T09:17:13+01:00" level=debug msg="Resources to fetch: [validatingwebhookconfigurations.admissionregistration.k8s.io]"
time="2020-11-18T09:17:13+01:00" level=debug msg="Resources to fetch: [customresourcedefinitions.apiextensions.k8s.io]"
time="2020-11-18T09:17:13+01:00" level=debug msg="Resources to fetch: [apiservices.apiregistration.k8s.io]"
time="2020-11-18T09:17:13+01:00" level=debug msg="Resources to fetch: [controllerrevisions.apps]"
time="2020-11-18T09:17:14+01:00" level=debug msg="Resources to fetch: [daemonsets.apps]"
time="2020-11-18T09:17:14+01:00" level=debug msg="Resources to fetch: [deployments.apps]"
time="2020-11-18T09:17:14+01:00" level=debug msg="Resources to fetch: [replicasets.apps]"
time="2020-11-18T09:17:14+01:00" level=debug msg="Resources to fetch: [statefulsets.apps]"
time="2020-11-18T09:17:14+01:00" level=debug msg="Resources to fetch: [deploymentconfigs.apps.openshift.io]"
time="2020-11-18T09:17:15+01:00" level=debug msg="Resources to fetch: [applications.argoproj.io]"
time="2020-11-18T09:17:15+01:00" level=debug msg="Resources to fetch: [appprojects.argoproj.io]"
time="2020-11-18T09:17:16+01:00" level=debug msg="Resources to fetch: [argocdexports.argoproj.io]"
time="2020-11-18T09:17:17+01:00" level=debug msg="Resources to fetch: [argocds.argoproj.io]"
time="2020-11-18T09:17:17+01:00" level=debug msg="Resources to fetch: [clusterworkflowtemplates.argoproj.io]"
time="2020-11-18T09:17:17+01:00" level=debug msg="Resources to fetch: [cronworkflows.argoproj.io]"
time="2020-11-18T09:17:17+01:00" level=debug msg="Resources to fetch: [workfloweventbindings.argoproj.io]"
time="2020-11-18T09:17:17+01:00" level=debug msg="Resources to fetch: [workflows.argoproj.io]"
time="2020-11-18T09:17:17+01:00" level=debug msg="Resources to fetch: [clusterrolebindings.authorization.openshift.io]"
time="2020-11-18T09:17:17+01:00" level=debug msg="Resources to fetch: [clusterroles.authorization.openshift.io]"
time="2020-11-18T09:17:17+01:00" level=debug msg="Resources to fetch: [workflowtemplates.argoproj.io]"
time="2020-11-18T09:17:17+01:00" level=debug msg="Resources to fetch: [rolebindingrestrictions.authorization.openshift.io]"
time="2020-11-18T09:17:17+01:00" level=debug msg="Resources to fetch: [rolebindings.authorization.openshift.io]"
time="2020-11-18T09:17:17+01:00" level=debug msg="Resources to fetch: [roles.authorization.openshift.io]"
time="2020-11-18T09:17:17+01:00" level=debug msg="Resources to fetch: [horizontalpodautoscalers.autoscaling]"
time="2020-11-18T09:17:17+01:00" level=debug msg="Resources to fetch: [clusterautoscalers.autoscaling.openshift.io]"
time="2020-11-18T09:17:17+01:00" level=warning msg="Cannot fetch: Unable to list \"image.openshift.io/v1, Resource=imagestreamimages\": the server could not find the requested resource"
time="2020-11-18T09:17:17+01:00" level=debug msg="Resources to fetch: [machineautoscalers.autoscaling.openshift.io]"
time="2020-11-18T09:17:17+01:00" level=debug msg="Resources to fetch: [cronjobs.batch]"
time="2020-11-18T09:17:17+01:00" level=debug msg="Resources to fetch: [jobs.batch]"
time="2020-11-18T09:17:17+01:00" level=debug msg="Resources to fetch: [sealedsecrets.bitnami.com]"
time="2020-11-18T09:17:17+01:00" level=debug msg="Resources to fetch: [buildconfigs.build.openshift.io]"
time="2020-11-18T09:17:18+01:00" level=debug msg="Resources to fetch: [builds.build.openshift.io]"
time="2020-11-18T09:17:18+01:00" level=debug msg="Resources to fetch: [certificatesigningrequests.certificates.k8s.io]"
time="2020-11-18T09:17:20+01:00" level=debug msg="Requests done (elapsed 16s)"
time="2020-11-18T09:17:20+01:00" level=debug msg="Using tabwriter"
time="2020-11-18T09:17:20+01:00" level=debug msg="Wrapping *printer.TablePrinter with FlattenListAdapterPrinter"
time="2020-11-18T09:17:20+01:00" level=fatal msg="print list item: print list item: object does not implement the Object interfaces"

**Comment by corneliusweig** [comment]
The failure states that the object that was being printed does not implement the `Object` interfaces. There's not much one can do about that. Since you are running OpenShift and not vanilla kubernetes, this is likely caused by some OpenShift specific resource type.

One of the promises of `ketall` is that it really prints everything. So I don't want to swallow this failure and work around. In that sense, even a `log.Warning` is not enough IMO. My favorite option to make this OpenShift friendlier is to print a message that tells what resources to explicitly `--exclude`.

So could you find out the offending resources for me? I don't have access to an OS cluster.

**Comment by lbohnsac** [comment]
I can give you access to my private test OCP cluster if you want!
Just write me an email!
It worked on a 4.3 OCP cluster with an older version of get-all like a charm!

**Comment by corneliusweig** [comment]
Do I understand correctly that older get-all versions work with the same cluster, whereas new get-all versions do not?
Maybe there's a problem in one of the dependencies. I'll release a new version shortly. Can you check if the problem persists with v1.3.6?

**Comment by git001** [comment]
@corneliusweig Yes, with the current version v1.3.6 is this fatal still raised.
OpenShift: 4.5.16
